variables:
- group: dev

name: $(variable_group_param) 

stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'service_connection'
                  subscriptionId: '003b772f-91e8-40ec-9470-b63ff9aac613'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'RGLab2_1'
                  location: 'northeurope'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/vnet.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/vnet.parameters.json'
